### ISSUE TITLE
bug: edit flashcards not working

### ISSUE THREAD

**Issue by noahlabear** [bynery-main/limonata-notion-clone#168]
currently there is a separate arrow keys to rename questions and asnwers as index needs to be adjusted by the arrows inside the flashcards component instead of the arrows below

**Comment by NatanAmado** [comment]
In order to include the editing, adding and deleting logic to the flashcards component would be major refactoring task that I don't think is really worth it now. I improved the UI to include the elements into the layout better into the whole page while keeping the logic where it is.

**Comment by ovirandunu** [comment]
how was this resolved?

**Comment by NatanAmado** [comment]
> how was this resolved?

Check out the branch. Specifically, commit 1ef21a5953575ec77b8f47d6d94719e047c377b1.
