### ISSUE TITLE
style: homepage hero section needs to be completed (VERY HIGH PRIORITY)

### ISSUE THREAD

**Issue by ovirandunu** [bynery-main/limonata-notion-clone#208]
- make the hero section responsive and center it on the home page. 
- pls make sure not to hardcode pixel values for widths and heights (inlucing margins) use relative values to the screensize
           eg - max-w-[50vw]

**Comment by ovirandunu** [comment]
Things that need to be included in the hero section text:

Make flashcards in seconds
Make study guides in seconds
Make and grade tests for you
Find the perfect answers
Compare notes with your peers
Ask questions on all your study resources

**Comment by noahlabear** [comment]
and on the second line, say something to the degree of:
Study together, with your friends and your AI
